name: Test Github Action

on: [push]

env:
  GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      gradlever: ${{ steps.gradle.outputs.stdout }}
    steps:
    - name: "Git clone"
      uses: actions/checkout@v2

    - name: "Set up JDK 17"
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - uses: gradle/gradle-build-action@v2.1.3
      id: gradle
      with:
        arguments: build --scan
        gradle-version: current
        cache-disabled: true
#    - name: "Get projet version in gradle"
#      uses: gradle/gradle-build-action@v2.1.3
#      id: gradle
#      with:
#        arguments: -q printVersion
#        gradle-version: current
#        cache-disabled: true
#
#    - id: gradle2
#      run: "./gradlew -q printVersion"
#    - name: "Echo release"
#      run: |
#         echo ${{ steps.gradle.outputs.stdout }}
#         echo ${{ toJSON(steps.gradle.outputs) }}
#         echo ${{ steps.gradle2.outputs.stdout }}
